import type { Metadata } from "next";
import "./globals.css";
import { kanit } from "./fonts/font";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`p-4 ${kanit.className} mb-20`}>
        {children}
        <Navbar />
      </body>
    </html>
  );
}
