import type { Metadata } from "next";
import "./globals.css";
import NavbarBottom from "./components/Navbar/NavbarBottom";
import NavbarHeader from "./components/Navbar/NavbarHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <NavbarHeader />
        {children}
        <NavbarBottom />
      </body>
    </html>
  );
}
